# Generated by Django 4.0.4 on 2022-05-25 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorName', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=100)),
                ('Country', models.CharField(blank=True, choices=[('Canada', 'Canada'), ('USA', 'USA')], max_length=20)),
                ('Category', models.CharField(max_length=100)),
                ('Ranking', models.IntegerField(blank=True)),
                ('desciption', models.TextField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('User', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff')),
            ],
        ),
    ]
