# Generated by Django 3.2.3 on 2022-05-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Website',
            field=models.CharField(max_length=100),
        ),
    ]
